package gui;

import excelOkuma.DosyaIslem;
import excelOkuma.Liste;
import excelOkuma.Ogrenci;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author gurcan
 */
public class Ana extends javax.swing.JFrame {

    /**
     * Creates new form Ana
     */
    public Ana() {

        model = new DefaultListModel();
        listeModel = new DefaultListModel();
        setTitle("Liste Otomasyonu");

        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sinifListe = new javax.swing.JList();
        sinifEkleButon = new javax.swing.JButton();
        sinifCikarButonu = new javax.swing.JButton();
        siniflariTemizleButonu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listeler = new javax.swing.JList();
        listeEkleButon = new javax.swing.JButton();
        listeCikarButonu = new javax.swing.JButton();
        listeTemizleButonu = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        sinifKapasiteEtiket = new javax.swing.JLabel();
        ogrenciKapasiteEtiket = new javax.swing.JLabel();
        durumEtiketi = new javax.swing.JLabel();
        dersAdiAlani = new javax.swing.JTextField();
        pdfUretButon = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ListeRadio = new javax.swing.JRadioButton();
        TutanakRadio = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sınıflar"));

        sinifListe.setModel(model     );
        jScrollPane1.setViewportView(sinifListe);

        sinifEkleButon.setText("Ekle");
        sinifEkleButon.setToolTipText("Listeye yeni sınıf ekler");
        sinifEkleButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinifEkleButonActionPerformed(evt);
            }
        });

        sinifCikarButonu.setText("Çıkar");
        sinifCikarButonu.setToolTipText("Seçilen sınıfı listeden çıkarır");
        sinifCikarButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinifCikarButonuActionPerformed(evt);
            }
        });

        siniflariTemizleButonu.setText("Tmzl");
        siniflariTemizleButonu.setToolTipText("Listedeki tüm sınıfları temizler");
        siniflariTemizleButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siniflariTemizleButonuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sinifCikarButonu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sinifEkleButon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(siniflariTemizleButonu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sinifEkleButon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sinifCikarButonu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(siniflariTemizleButonu)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Listeler"));

        listeler.setModel(listeModel);
        jScrollPane2.setViewportView(listeler);

        listeEkleButon.setText("Ekle");
        listeEkleButon.setToolTipText("Listeye yeni dosya eklemektedir.");
        listeEkleButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeEkleButonActionPerformed(evt);
            }
        });

        listeCikarButonu.setText("Çıkar");
        listeCikarButonu.setToolTipText("Listedeki seçili dosyayı çıkarır.");
        listeCikarButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeCikarButonuActionPerformed(evt);
            }
        });

        listeTemizleButonu.setText("Tmzl");
        listeTemizleButonu.setToolTipText("Listedeki tüm listeleri temizler.");
        listeTemizleButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeTemizleButonuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listeCikarButonu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listeTemizleButonu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listeEkleButon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(listeEkleButon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listeCikarButonu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listeTemizleButonu)))
                .addGap(12, 12, 12))
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        sinifKapasiteEtiket.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        sinifKapasiteEtiket.setText("Sınıf kapasitesi : ");

        ogrenciKapasiteEtiket.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        ogrenciKapasiteEtiket.setText("Öğrenci sayısı  : ");

        durumEtiketi.setText("? öğrenci açıkta");

        pdfUretButon.setText("PDF ÜRET");
        pdfUretButon.setToolTipText("Öğrenci listesi oluşturmaktadır");
        pdfUretButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdfUretButonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Ders Adı");

        buttonGroup1.add(ListeRadio);
        ListeRadio.setSelected(true);
        ListeRadio.setText("Liste");

        buttonGroup1.add(TutanakRadio);
        TutanakRadio.setText("Tutanak");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(ogrenciKapasiteEtiket, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(10, 10, 10)
                        .addComponent(dersAdiAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(sinifKapasiteEtiket, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(durumEtiketi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TutanakRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ListeRadio)))
                .addGap(38, 38, 38)
                .addComponent(pdfUretButon, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ListeRadio)
                            .addComponent(TutanakRadio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dersAdiAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sinifKapasiteEtiket)
                            .addComponent(durumEtiketi))
                        .addGap(18, 18, 18)
                        .addComponent(ogrenciKapasiteEtiket)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addComponent(pdfUretButon, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel1, jPanel2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sinifEkleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinifEkleButonActionPerformed
        // TODO add your handling code here:
        sinifEkle();
    }//GEN-LAST:event_sinifEkleButonActionPerformed

    private void listeEkleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listeEkleButonActionPerformed
        listeEkle();

    }//GEN-LAST:event_listeEkleButonActionPerformed

    private void pdfUretButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdfUretButonActionPerformed
        pdfUret();
    }//GEN-LAST:event_pdfUretButonActionPerformed

    private void sinifCikarButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinifCikarButonuActionPerformed
        // TODO add your handling code here:
        sinifCikar();
    }//GEN-LAST:event_sinifCikarButonuActionPerformed

    private void listeCikarButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listeCikarButonuActionPerformed
        // TODO add your handling code here:
        listeCikar();
    }//GEN-LAST:event_listeCikarButonuActionPerformed

    private void siniflariTemizleButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siniflariTemizleButonuActionPerformed
        // TODO add your handling code here:
        siniflariTemizle();
    }//GEN-LAST:event_siniflariTemizleButonuActionPerformed

    private void listeTemizleButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listeTemizleButonuActionPerformed
        // TODO add your handling code here:
        listeleriTemizle();
    }//GEN-LAST:event_listeTemizleButonuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ana().setVisible(true);
            }
        });
    }
    private DefaultListModel model;
    private DefaultListModel listeModel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ListeRadio;
    private javax.swing.JRadioButton TutanakRadio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField dersAdiAlani;
    private javax.swing.JLabel durumEtiketi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton listeCikarButonu;
    private javax.swing.JButton listeEkleButon;
    private javax.swing.JButton listeTemizleButonu;
    private javax.swing.JList listeler;
    private javax.swing.JLabel ogrenciKapasiteEtiket;
    private javax.swing.JButton pdfUretButon;
    private javax.swing.JButton sinifCikarButonu;
    private javax.swing.JButton sinifEkleButon;
    private javax.swing.JLabel sinifKapasiteEtiket;
    private javax.swing.JList sinifListe;
    private javax.swing.JButton siniflariTemizleButonu;
    // End of variables declaration//GEN-END:variables

    public DefaultListModel getModel() {
        return model;
    }

    public DefaultListModel getListeModel() {
        return listeModel;
    }

    private void sinifEkle() {
        SinifUi sinifAl = new SinifUi(this);
        sinifAl.setLocationRelativeTo(sinifEkleButon);
        sinifAl.setVisible(true);
    }

    public void sayilariGuncelle() {
        sinifKapasiteAyarla();
        ogrenciSayisiAyarla();
        durumAyarla();
    }

    public void sinifKapasiteAyarla() {
        sinifKapasiteEtiket.setText("Sınıf Kapasitesi : " + Integer.toString(sinifKapasiteBul()));
    }

    public void ogrenciSayisiAyarla() {
        ogrenciKapasiteEtiket.setText("Öğrenci Sayısı : " + Integer.toString(ogrenciSayisiGetir()));
    }

    /**
     * uyarı kısımları ayarlanıyor
     */
    public void durumAyarla() {

        int fark = sinifKapasiteBul() - ogrenciSayisiGetir();

        if ((fark < 0)) {
            durumEtiketi.setText(Integer.toString(Math.abs(fark)) + " öğrenci açıkta kaldı");
            durumEtiketi.setForeground(Color.red);
        } else if (fark > 0) {
            durumEtiketi.setText(Integer.toString(Math.abs(fark)) + " yer boş kaldı");
            durumEtiketi.setForeground(Color.magenta);
        } else {
            durumEtiketi.setText("öğrenci ve yer sayısı eşit.");
            durumEtiketi.setForeground(Color.BLACK);
        }
    }

    public Object[] siniflariAl() {
        return model.toArray();
    }

    public Object[] listeleriAl() {
        return listeModel.toArray();
    }

    /**
     * tüm sınıfların kapasiteleri hesaplanıp ekrana basılıyor.
     */
    public int sinifKapasiteBul() {
        int kapasite = 0;

        kapasite = DosyaIslem.sinifToplamKapasiteBul(siniflariAl());

        return kapasite;
    }

    public int ogrenciSayisiGetir() {
        int kapasite = 0;

        kapasite = DosyaIslem.ogrenciToplamSayiBul(listeleriAl());

        return kapasite;
    }

    private void listeEkle() {
        JFileChooser c = new JFileChooser();
        c.setMultiSelectionEnabled(true);
        c.addChoosableFileFilter(new FileNameExtensionFilter("Excel Dosyası", "xlsx"));

        // Demonstrate "Save" dialog:
        int rVal = c.showSaveDialog(listeEkleButon);

        if (rVal == JFileChooser.APPROVE_OPTION) {

            File[] files = c.getSelectedFiles();

            for (File f : files) {

                Liste liste = new Liste(f);

                if (!listeModel.contains(liste)) {

                    listeModel.addElement(liste);

                    sayilariGuncelle();
                } else {
                    JOptionPane.showMessageDialog(listeEkleButon, "Dosya listede mevcut.", "UYARI", JOptionPane.ERROR_MESSAGE);
                }

            }
        }//end-of
        if (rVal == JFileChooser.CANCEL_OPTION) {

            System.out.println("iptal");
        }
    }

    private void pdfUret() {
        DosyaIslem islem = new DosyaIslem();
        ArrayList<Ogrenci> ogrenciler = islem.ogrenciSiraliSinifAta(listeleriAl(), siniflariAl());

        try {

            if (ogrenciler == null) {
                JOptionPane.showMessageDialog(pdfUretButon, "Dosya üretilemedi !!");
            } else {

                if (ListeRadio.isSelected()) {
                    islem.ogrenciNumaraliListepdfYazdir(ogrenciler, dersAdiAlani.getText());
                } else if (TutanakRadio.isSelected()) {
                    islem.tutanakpdfYazdir(ogrenciler, dersAdiAlani.getText());
                }
            }
        } catch (JRException ex) {
            Logger.getLogger(Ana.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void sinifCikar() {
        if (!sinifListe.isSelectionEmpty()) {
            model.remove(sinifListe.getSelectedIndex());
            sayilariGuncelle();
        }
    }

    private void listeCikar() {
        if (!listeler.isSelectionEmpty()) {
            listeModel.remove(listeler.getSelectedIndex());
            sayilariGuncelle();
        }
    }

    /**
     * Listedeki tüm elemanları silmektedir.
     */
    private void siniflariTemizle() {

        model.removeAllElements();
        sayilariGuncelle();

    }

    private void listeleriTemizle() {
        listeModel.removeAllElements();
        sayilariGuncelle();
    }
}
